apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: n35lz04ox-nodejs 
  janus-idp.io/tekton: n35lz04ox-nodejs
  backstage.io/kubernetes-id: n35lz04ox-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: n35lz04ox-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml